### ISSUE TITLE
Modulo de Menus (simples - facil)

### ISSUE THREAD

**Issue by abraaoribeiro23** [Comrade-Software-Ltda/comrade-intl-net6#3]

**Comment by yakkumo** [comment]
public class Menu
    {
        public Menu Pai { get; set; }
        public List<Menu> SubMenus { get; set; }
        public string Id { get; set; }
        public string Text { get; set; }
        public string Description { get; set; }
        public string Order { get; set; } <- talvez
        public string Route{ get; set; } <- talvez
    }
